/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, AppConfig } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { DbService } from "src/dbService/db.service";

export class AppConfigServiceBase {
  constructor(protected readonly prisma: DbService) {}

  async count<T extends Prisma.AppConfigFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppConfigFindManyArgs>
  ): Promise<number> {
    return await this.prisma.appConfig.count(args);
  }

  async findMany<T extends Prisma.AppConfigFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppConfigFindManyArgs>
  ): Promise<PaginatedInterface<AppConfig>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.appConfig.findMany(args),
      this.prisma.appConfig.count({ where: { deletedAt: null } }),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.AppConfigFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppConfigFindUniqueArgs>
  ): Promise<AppConfig | null> {
    return await this.prisma.appConfig.findUnique(args);
  }
  async create<T extends Prisma.AppConfigCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppConfigCreateArgs>
  ): Promise<AppConfig> {
    return await this.prisma.appConfig.create<T>(args);
  }
  async createMany<T extends Prisma.AppConfigCreateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppConfigCreateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.appConfig.createMany<T>(args);
  }
  async update<T extends Prisma.AppConfigUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppConfigUpdateArgs>
  ): Promise<AppConfig> {
    return await this.prisma.appConfig.update<T>(args);
  }
  async delete<T extends Prisma.AppConfigDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppConfigDeleteArgs>
  ): Promise<AppConfig> {
    return await this.prisma.appConfig.delete(args);
  }

  async updateMany<T extends Prisma.AppConfigUpdateManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AppConfigUpdateManyArgs>
  ): Promise<Prisma.BatchPayload> {
    return await this.prisma.appConfig.updateMany(args);
  }
}
